"""Type stubs for edge_tts package."""

from typing import List, Dict, Any, Optional


class Communicate:
    def __init__(self, text: str, voice: str, rate: Optional[str] = None,
                 volume: Optional[str] = None, pitch: Optional[str] = None,
                 proxy: Optional[str] = None) -> None: ...
    async def save(self, outfile: str) -> None: ...
    async def stream(self): ...
    async def write_to_file(self, outfile: str) -> None: ...


async def list_voices() -> List[Dict[str, Any]]: ...
async def voices() -> List[Dict[str, Any]]: ...
